version: 2

builds:
  - id: shireguard
    dir: client
    main: ./cmd/shireguard
    binary: shireguard
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64

  - id: shireguard-relay
    dir: relay
    main: ./cmd/shireguard-relay
    binary: shireguard-relay
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - arm64
      - amd64

archives:
  - id: client
    builds:
      - shireguard
    name_template: "shireguard_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

  - id: relay
    builds:
      - shireguard-relay
    name_template: "shireguard-relay_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

brews:
  - name: shireguard
    ids:
      - client
    repository:
      owner: doppiscantsleep
      name: homebrew-shireguard
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://shireguard.com"
    description: "WireGuard P2P connectivity"
    directory: Formula
    install: |
      bin.install "shireguard"
    test: |
      system "#{bin}/shireguard", "--version"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
