name = "shireguard-api"
main = "src/index.ts"
compatibility_date = "2025-02-14"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.sh"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.jpeg", "**/*.jpg", "**/*.png", "**/*.ico"]
fallthrough = false

[[d1_databases]]
binding = "DB"
database_name = "shireguard-db"
database_id = "29080334-bc8c-4853-afd1-371017bb5b33"
migrations_dir = "src/db/migrations"

[durable_objects]
bindings = [
  { name = "SIGNALING", class_name = "SignalingRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]

[[kv_namespaces]]
binding = "KV"
id = "e0fc4179e9894bbc9b6c42b2b7c6c276"

[triggers]
crons = ["0 3 * * *"]  # 3am UTC daily
